# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-22 03:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=200)),
                ('time', models.DateTimeField(verbose_name='Build time')),
                ('revision', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=25)),
                ('next_number', models.IntegerField(default=1)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builds.Artifact')),
            ],
        ),
        migrations.AddField(
            model_name='build',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builds.Version'),
        ),
        migrations.AlterUniqueTogether(
            name='version',
            unique_together=set([('artifact', 'version')]),
        ),
        migrations.AlterUniqueTogether(
            name='build',
            unique_together=set([('version', 'number')]),
        ),
    ]
