# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('builds', '0002_auto_20170227_2112'), ('builds', '0003_auto_20170227_2122'), ('builds', '0004_auto_20170227_2129')]

    dependencies = [
        ('builds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='component',
            name='name',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='versionbase',
            name='value',
            field=models.CharField(db_index=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='build',
            name='branch',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='build',
            name='revision',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
