# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-24 06:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0004_auto_20170222_0609'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewBuild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=25)),
                ('branch', models.CharField(max_length=200)),
                ('revision', models.CharField(max_length=100)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='build',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='builds.Version'),
        ),
        migrations.AlterField(
            model_name='version',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='builds.Application'),
        ),
    ]
